run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gocyclo:
    min-complexity: 10
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  goimports:
    local-prefixes: github.com/abdurrahimagca/go-api-starter
  
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentedOutCode

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - goconst
    - dupl
    - lll
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - nolintlint

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/api/gen.go
      linters:
        - lll
        - dupl
        - unused
        - gocritic
        - gocyclo
    - path: internal/sqlc/
      linters:
        - lll
        - dupl
        - unused
        - gocritic
    - linters:
        - lll
      source: "^//go:generate"