// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Labubu struct {
	ID   int32       `json:"id"`
	Text pgtype.Text `json:"text"`
}
