openapi: 3.0.0
info:
  title: Go API Starter
  description: A simple Go API template with labubu endpoints
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /login:
    $ref: './paths/auth.yaml#/login'
  /labubu:
    $ref: './paths/labubu.yaml#/labubu'

components:
  schemas:
    LoginResponse:
      $ref: './components/schemas.yaml#/components/schemas/LoginResponse'
    CreateLabubuRequest:
      $ref: './components/schemas.yaml#/components/schemas/CreateLabubuRequest'
    Labubu:
      $ref: './components/schemas.yaml#/components/schemas/Labubu'